### PR TITLE
remove sed -i --> php7 in .htaccess

### PR DESCRIPTION
**Pull request by enoch85**
In 9.1 the .htaccess files has 2 entries. One for php5 and one for php7.

### CODE REVIEW

**Comment by ezraholm50** [comment]
Could you explain as I implemented it as well on BerryCloud.

**Comment by enoch85** [comment]
This will be in 9.0.1 even, so I will change this PR and commit it tonite. Just follow what I've done, or take a look in .htaccess and you will see.

**Comment by ezraholm50** [comment]
You mean that there wont be a version specified right? so its just <if mod_php> or something similar?

**Comment by enoch85** [comment]
@ezraholm50 Both php5 and php7 will be specified.

**Comment by ezraholm50** [comment]
thats nearly the same i guess, got it thx.

**Comment by enoch85** [comment]
done

**Pull request closed without merging**
